name: Generate Contribution Snake GIF

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake files (GIF + SVG)
        uses: Platane/snk@v3
        with:
          github_user_name: Hardik-Kumar0005
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake.gif?color_snake=00aaff&color_dots=#0d1117,#0d1117,#0d1117,#0d1117,#0d1117

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
